// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjiyqxfotpfwdiwdexzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqaXlxeGZvdHBmd2Rpd2RleHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzNzQyNzEsImV4cCI6MjA3ODk1MDI3MX0.jNhxybxDSnuJt8-vMgF_ZRM_cH-x7V_aAFlnEydpHGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);